"""Provider-neutral local control plane for clusters and persistent jobs."""

from lambdaforge.LazyExports import LazyExports

_NAMES = (
    "ClusterAuthentication",
    "ClusterBootstrapResult",
    "ClusterCatalog",
    "ClusterProfile",
    "ClusterService",
    "ClusterStoragePolicy",
    "CommandResult",
    "ControlPlane",
    "ControlPlaneFactory",
    "CredentialProvider",
    "CredentialService",
    "CudaCompatibilityResolver",
    "Doctor",
    "DoctorCheck",
    "DoctorReport",
    "EnvironmentCredentialProvider",
    "EnvironmentIdentity",
    "EnvironmentProvider",
    "ExecutionBundle",
    "ExecutionBundleBuilder",
    "ExecutionProfile",
    "ExistingEnvironmentProvider",
    "InteractiveCredentialProvider",
    "JobGroup",
    "JobGroupStore",
    "JobHandle",
    "JobRecord",
    "JobService",
    "JobState",
    "JobStore",
    "LocalScheduler",
    "LocalTransport",
    "ManagedEnvironmentProvider",
    "MultiClusterSubmissionService",
    "OverviewService",
    "PasswordSshTransport",
    "PreparedEnvironment",
    "ProcessIdentity",
    "ProcessScheduler",
    "ProcessSupervisor",
    "ProjectWheelBuilder",
    "ResourceService",
    "ResourceSnapshot",
    "Scheduler",
    "SchedulerCapabilities",
    "SchedulerCommand",
    "SchedulerSubmission",
    "SecretRedactor",
    "SlurmClusterResourceProbe",
    "SlurmProfile",
    "SlurmResourceMapping",
    "SlurmScheduler",
    "SshConnectionPolicy",
    "SshTransport",
    "StorageGcPlan",
    "StorageReport",
    "StorageService",
    "SystemKeyringCredentialProvider",
    "TorchInstallationPlan",
    "TorchInstallationPolicy",
    "Transport",
)

LazyExports.install(
    __name__,
    {name: (f"lambdaforge.controlplane.{name}", name) for name in _NAMES},
)

__all__ = list(_NAMES)
