"""Stable public API for binary and multiclass classification metrics."""

from lambdaforge.metrics.classification.binary import (
    BinaryAccuracy,
    BinaryAUPRC,
    BinaryAUROC,
    BinaryBalancedAccuracy,
    BinaryCohenKappa,
    BinaryConfusionCounts,
    BinaryConfusionMetric,
    BinaryF1,
    BinaryMCC,
    BinaryPrecision,
    BinaryRecall,
    BinarySpecificity,
    StreamingBinaryAUPRC,
    StreamingBinaryAUROC,
    StreamingBinaryCurveMetric,
)
from lambdaforge.metrics.classification.multiclass import (
    MulticlassAccuracy,
    MulticlassAUPRC,
    MulticlassAUROC,
    MulticlassBalancedAccuracy,
    MulticlassCurveAverage,
    MulticlassF1,
    MulticlassMetric,
    StreamingMulticlassAUPRC,
    StreamingMulticlassAUROC,
    StreamingMulticlassCurveMetric,
    UndefinedClassPolicy,
)

__all__ = [
    "BinaryAccuracy",
    "BinaryAUPRC",
    "BinaryAUROC",
    "BinaryBalancedAccuracy",
    "BinaryCohenKappa",
    "BinaryConfusionCounts",
    "BinaryConfusionMetric",
    "BinaryF1",
    "BinaryMCC",
    "BinaryPrecision",
    "BinaryRecall",
    "BinarySpecificity",
    "MulticlassAccuracy",
    "MulticlassAUPRC",
    "MulticlassAUROC",
    "MulticlassBalancedAccuracy",
    "MulticlassCurveAverage",
    "MulticlassF1",
    "MulticlassMetric",
    "StreamingBinaryAUPRC",
    "StreamingBinaryAUROC",
    "StreamingBinaryCurveMetric",
    "StreamingMulticlassAUPRC",
    "StreamingMulticlassAUROC",
    "StreamingMulticlassCurveMetric",
    "UndefinedClassPolicy",
]
